export const NODE_CONNECTIONS = [
  { from: { x: 80, y: 150 }, to: { x: 160, y: 60 } },
  { from: { x: 360, y: 320 }, to: { x: 560, y: 300 } },
  { from: { x: 160, y: 440 }, to: { x: 360, y: 440 } },
  { from: { x: 360, y: 440 }, to: { x: 560, y: 440 } },
  { from: { x: 160, y: 680 }, to: { x: 360, y: 680 } },
  { from: { x: 360, y: 680 }, to: { x: 560, y: 680 } },
  { from: { x: 560, y: 680 }, to: { x: 760, y: 680 } },
  { from: { x: 760, y: 680 }, to: { x: 760, y: 90 } },
  { from: { x: 560, y: 560 }, to: { x: 760, y: 300 } },
  { from: { x: 160, y: 800 }, to: { x: 360, y: 800 } },
  { from: { x: 360, y: 800 }, to: { x: 560, y: 800 } },
  { from: { x: 560, y: 800 }, to: { x: 760, y: 800 } },
  { from: { x: 760, y: 800 }, to: { x: 760, y: 920 } },
  { from: { x: 160, y: 920 }, to: { x: 360, y: 920 } },
  { from: { x: 360, y: 920 }, to: { x: 560, y: 920 } },
  { from: { x: 560, y: 920 }, to: { x: 760, y: 920 } },
  { from: { x: 760, y: 920 }, to: { x: 760, y: 90 } },
];

export const DEFAULT_VFX_STATE = {
  halation: 0,
  grain: 0,
  motionBlur: 0,
  beauty: 0,
  rayTracing: { enabled: false, intensity: 50, samples: 32, bounces: 2, denoise: true },
  relighting: {
    enabled: false,
    intensity: 50,
    lightPosition: { x: 0, y: 0, z: 1 },
    lightColor: '#ffffff',
    faceMapping: true,
  },
  denoising: { enabled: false, strength: 50, temporalWeight: 0.5, mode: 'cinematic' },
  inPainting: { enabled: false, targetId: '', propagation: true, fillMode: 'neural_dream' },
  depthMap: { enabled: false, intensity: 50, focalPoint: 0.5, visualization: false },
  styleDNA: { signature: '', intensity: 50, colorBias: 0.5, textureBias: 0.5 },
  bokeh: { enabled: false, aperture: 2.8, shape: 'circle', highlightBoost: 1.0 },
  colorMatch: { referenceClipId: '', lumaMatch: 1.0, chromaMatch: 1.0 },
  volumetrics: {
    enabled: false,
    density: 0.1,
    anisotropy: 0.5,
    shadows: true,
    neuralAtmosphere: true,
  },
  procedural: { vexCode: 'v@P += noise(v@P * 2.0);', seed: 42, complexity: 5, isActive: false },
  temporalConsistency: {
    enabled: true,
    flowWeight: 0.8,
    historyBuffer: 5,
    neuralDeflicker: true,
  },
  realitySynthesis: {
    enabled: false,
    nerfModelId: '',
    cameraPath: '',
    focalDepth: 0.5,
    reconstructionQuality: 0.8,
  },
  quantumSimulation: {
    type: 'fluid',
    viscosity: 0.5,
    turbulence: 0.5,
    vorticity: 0.5,
    neuralEnhancement: true,
    isActive: false,
  },
  holographicDepth: { enabled: false, planes: 256, lightFieldIntensity: 1.0, parallaxStrength: 1.0 },
  sentientLogic: {
    enabled: false,
    narrativeIntent: 'Cinematic Drama',
    emotionalBias: 0,
    autonomousAdjustment: true,
  },
  multiversalBranching: { active: false, branchSeed: 'B-001', divergenceFactor: 0.2, realityBlend: 0.5 },
  bioDigitalSim: {
    type: 'growth',
    organicWeight: 0.5,
    evolutionSpeed: 0.5,
    dnaSignature: 'N-CELL-99',
  },
  causalEngineering: {
    enabled: false,
    causalityShift: 0,
    entropyControl: 1.0,
    effectBeforeCause: false,
  },
  noeticSynthesis: {
    enabled: false,
    archetypeId: 'Hero',
    consciousnessSync: 0.5,
    manifestationStrength: 0.5,
  },
  ontologicalVariables: {
    gravityConstant: 1.0,
    lightSpeedShift: 1.0,
    timeDilation: 1.0,
    physicalLawDivergence: 0,
  },
  hyperDimensional: {
    active: false,
    dimensionScale: 3.0,
    parallaxFolding: 0.5,
    nonEuclideanGeometry: false,
  },
  recursiveSingularity: { enabled: false, recursionDepth: 1, neuralFractalMode: true, detailIntensity: 0.5 },
  akashicSourcing: { enabled: false, dataStream: 'history', hallucinationDepth: 0.5, sourcingQuery: '' },
  zeroPointEnergy: { active: false, vacuumFluctuation: 0.1, radianceIntensity: 1.0, energyStability: 0.8 },
  quantumEntanglement: {
    isEntangled: false,
    targetClipId: '',
    propertySync: 'all',
    entanglementStrength: 1.0,
  },
  metaNarrative: {
    enabled: false,
    symbolismWeight: 0.5,
    subtextVisualization: true,
    archetypalOverlayId: '',
  },
};
